# Created with package:mono_repo v2.3.0
language: dart

jobs:
  include:
    - stage: analyze
      name: "SDK: dev; PKG: packages/migrate_base; TASKS: `dartanalyzer --fatal-infos --fatal-warnings .`"
      dart: dev
      os: linux
      env: PKGS="packages/migrate_base"
      script: ./tool/travis.sh dartanalyzer
    - stage: analyze
      name: "SDK: dev; PKG: packages/migrate_to_1; TASKS: `dartanalyzer --fatal-infos --fatal-warnings .`"
      dart: dev
      os: linux
      env: PKGS="packages/migrate_to_1"
      script: ./tool/travis.sh dartanalyzer
    - stage: unit_test
      name: "SDK: dev; PKG: packages/migrate_base; TASKS: `pub run test`"
      dart: dev
      os: linux
      env: PKGS="packages/migrate_base"
      script: ./tool/travis.sh test
    - stage: unit_test
      name: "SDK: dev; PKG: packages/migrate_to_1; TASKS: `pub run test`"
      dart: dev
      os: linux
      env: PKGS="packages/migrate_to_1"
      script: ./tool/travis.sh test

stages:
  - analyze
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
