name: migrate_to_1
description: A tool for migrating depndent packages to support the 1.0.0 version.
version: 0.0.1+1
homepage: https://github.com/amirh/dart_lsc/tree/master/packages/migrate_to_1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.3
  file: ^5.1.0
  pubspec_parse: ^0.1.5
  pub_semver: ^1.4.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
