name: dart_lsc
description: A tool for shepherding Large Scale Changes in the Dart ecosystem.
version: 0.0.2+1
homepage: https://github.com/amirh/dart_lsc/tree/master/packages/dart_lsc

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.3
  file: ^5.1.0
  http: ^0.12.0+4
  meta: ^1.1.8
  path: ^1.6.4
  pub_semver: ^1.4.3
  pubspec_parse: ^0.1.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
