name: dart_lsc
description: A tool for shepherding Large Scale Changes in the Dart ecosystem.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.3
  http: ^0.12.0+4
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
