name: migrate_base
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

dependencies:
  args: ^1.6.0
  file: ^5.2.1
  meta: ^1.2.3

dev_dependencies:
  test: ^1.15.4
  mockito: ^4.1.2

environment:
  sdk: '>=2.7.0 <3.0.0'
